version: '3.8'
services:
  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  recommendation-adapter:
    build: ./recommendation-adapter
    ports:
      - "3002:3002"
    environment:
      - PYTHON_SERVICE_URL=http://python-recommendation:5000
    depends_on:
      - python-recommendation
  python-recommendation:
    build: ./python-recommendation-service
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MODEL_PATH=/app/models/recommendation_model.pkl
    volumes:
      - ./python-recommendation-service:/app
    depends_on:
      - redis
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  pgdata:
